package com.notianotes.app.render

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.DrawScope
import com.notianotes.app.freehand.Point

/**
 * High-Fidelity Freehand Renderer
 * Renders the outline EXACTLY as generated by the algorithm.
 * Since the algorithm now handles smoothing (catmull-rom), we use simple lines here
 * to avoid shrinking/distortion artifacts.
 */
object FreehandRenderer {

    fun drawOutline(
        drawScope: DrawScope,
        outline: List<Point>,
        color: Color,
        isEraser: Boolean = false
    ) {
        if (outline.size < 3) return
        
        val path = createSmoothPath(outline)
        drawScope.drawPath(
            path = path,
            color = if (isEraser) Color.White else color
        )
    }

    /**
     * Create path from outline using direct lines.
     * RELIES ON ALGORITHM FOR SMOOTHNESS.
     */
    fun createSmoothPath(outline: List<Point>): Path {
        if (outline.isEmpty()) return Path()
        
        val path = Path()
        
        // İlk noktaya git
        val start = outline.first()
        path.moveTo(start.x, start.y)
        
        // Diğer tüm noktaları birleştir
        // Algoritma zaten ara noktaları (Catmull-Rom) ile doldurduğu için
        // buradaki düz çizgiler gözle görülmeyecek kadar küçük ve pürüzsüz olacak.
        for (i in 1 until outline.size) {
            val p = outline[i]
            path.lineTo(p.x, p.y)
        }
        
        path.close()
        return path
    }
    
    fun createCachedPath(outline: List<Point>): Path {
        return createSmoothPath(outline)
    }
}